### ISSUE TITLE
An erratum on README file.

### ISSUE THREAD

**Issue by hamidify** [pdrabinski/GAN_Colorizer#1]
> If it is fooled by the `Discriminator` too early then it is not doing its job well enough and as a result, will not be able to train the Generator well.
Should be
> If it is fooled by the `Generator` too early then it is not doing its job well enough and as a result, will not be able to train the Generator well.

[Discriminator](https://github.com/pdrabinski/GAN_Colorizer/blob/master/README.md#discriminator)

**Comment by pdrabinski** [comment]
Thanks!
